name: Bump Version
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths: ["*.js"]

jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-24.04
    concurrency: bump-${{github.head_ref}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Setup Node.JS
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          cache: npm

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@fdad52b3b3bbe8fad96b8ca18c56127a96f603db # v11.0.7
        with:
          tag-prefix: 'v'
        env:
          token: ${{secrets.TOKEN || secrets.GITHUB_TOKEN}}
          ref: ${{github.head_ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: cat package.json
        run: cat ./package.json

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
